### ISSUE TITLE
Verbose output/debugging

### ISSUE THREAD

**Issue by mgrottenthaler** [gflohr/einvoice-eu#204]
First of all, very cool tool and great idea! I had fun trying to create an excel template and adapting the mapping.

Obviously I didn't get everything right from the beginning. There were some validation errors with the YAML file, mostly some elements missing. But now I only get the very generic error message `e-invoice-eu: Error: validation failed`

It would be great if there were an option to debug this.

**Comment by gflohr** [comment]
Thanks for the compliments! :)

I know what you mean with the non-verbose error message but I can never reproduce it, when I have time to fix it. Can you provide more detailed information?

**Comment by mgrottenthaler** [comment]
I will try to debug myself. But I am not very much into node.js. I saw in the help that there should be a `--verbose` flag. But that doesn't seem to be the case anymore.

I will attach my test files.

**Comment by mgrottenthaler** [comment]
I managed to debug/fix it myself. I think the biggest problem was that I misunderstood how sections work. I think this part was basically wrong:

``` yaml
meta:
  sectionColumn:
    Something-that-didnt-exist: F
  empty: [ '[:empty:]' ]
```

Anyhow, the original problem that the error messages are quite generic is still there. I would help, but I am really not a node.js programmer...

**Comment by gflohr** [comment]
Yes, I'll try to fix it, the next time I encounter the problem. It doesn't always appear.

**Comment by mgrottenthaler** [comment]
Okay I have some more info, because I encountered the error again.

I have this mapping.yaml

``` yaml
meta:
  sectionColumn:
    Invoice: F
    Data: A
  empty: [ '[:empty:]' ]
ubl:Invoice:
[...]
  cac:OrderReference:
    cbc:ID: =Data:DoesNotExist.B1
```

What happend:

`e-invoice-eu: Error: validation failed`

What would I expect:

```
Error in mapping file line XXX: cbc:ID: =Data:DoesNotExist.B1
- Couldn't find Data:DoesNotExist.B1 in spreadsheet
```
